name: Build and Push Docker Image into GHCR

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'
    
    - name: Grant execute permission for Maven wrapper
      run: chmod +x ./mvnw

    - name: Build Docker image
      run: ./mvnw spring-boot:build-image -DskipTests

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    # - name: Push Docker image to GitHub Container Registry
    #   run: |
    #     docker build . --tag ghcr.io/karimdevwm/currency-conversion-service:latest
    #     docker push ghcr.io/karimdevwm/currency-conversion-service:latest

    - name: Push Docker image to GitHub Container Registry
      run: |
        IMAGE_NAME=ghcr.io/karimdevwm/currency-conversion-service:latest
        docker push ghcr.io/karimdevwm/currency-conversion-service:latest